config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :models

  root 'pages#index'
  get 'pages/about' => 'high_voltage/pages#show', id: 'about'

  get '/volunteer/register', :as => 'volunteer_register',to: 'volunteer#new'
  post '/volunteer/login', :as => 'volunteer_login',to: 'volunteer#login'
  post '/contituent/login', :as => 'contituent_login',to: 'contituent#login'
  match '/volunteer/register', to: 'volunteer#create', via: [:post]

  get '/contituent/register', :as => 'contituent_register',to: 'contituent#new'
  match '/contituent/register', to: 'contituent#create', via: [:post]
   
  get '/admin', :as => 'admin_index',to: 'admin#index'
  get '/admin/upload', :as => 'admin_upload',to: 'admin#upload'

  match '/volunteer/home', to: 'volunteer#home', via: [:get]
  match '/volunteer/profile', to: 'volunteer#profile', via: [:get]
  match '/volunteer/reviews', to: 'volunteer#reviews', via: [:get]
  match '/volunteer/schedule', to: 'volunteer#schedule', via: [:get]
  match '/volunteer/settings', to: 'volunteer#settings', via: [:get]
  match '/contituent/home', to: 'contituents#home', via: [:get]
  match '/contituent/profile', to: 'contituents#profile', via: [:get]
  match '/contituent/reviews', to: 'contituents#reviews', via: [:get]
  match '/contituent/schedule', to: 'contituents#schedule', via: [:get]
  match '/contituent/settings', to: 'contituents33#settings', via: [:get]

end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/schedule.rb
class Schedule < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

    def index
    end

    def home
    end 

    def upload
        render 
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contituent_controller.rb
class ContituentController < ApplicationController

    def new
        @contituent = User.new
    end

    def create
        @constituent = User.create!(
                    name: params[:name],
                    password: params[:password],
                    avaliability_date: params[:avaliability_date],
                    phone: params[:phone],
                    gender: params[:gender],
                    referee_name: params[:referee_name],
                    refree_email: params[:refree_email],
                    referee_description: params[:referee_description]
                    )
        redirect_to '/contituent/register'
    end 

    def home
        @user = User.where(email: params[:email])
        puts @user
        render 'home'
    end 

    def login
        puts params
        @user = User.where(email: params[:email])
        puts @user
        render 'home'
    end

    def profile
    end

    def reviews
    end

    def settings
    end

    def schedule
    end 
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/controllers/volunteer_controller.rb
class VolunteerController < ApplicationController

    def new
        @volunteer = User.new
    end

    def login
        puts params
        @user = User.where(email: params[:email])
        puts @user
        render 'home'
    end

    def create
        puts params
        @volunteer = User.create!(
                    name: params[:name],
                    password: params[:password],
                    avaliability_date: params[:avaliability_date],
                    phone: params[:phone],
                    gender: params[:gender],
                    referee_name: params[:referee_name],
                    refree_email: params[:refree_email],
                    referee_description: params[:referee_description]
                    )
        redirect_to '/volunteer/register'
    end 

    def home
    end


    def profile
    end

    def reviews
    end

    def settings
    end

    def schedule
    end 

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contituents_helper.rb
module ContituentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/registration_helper.rb
module RegistrationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/volunteer_helper.rb
module VolunteerHelper
end

app/views/contituent/new.html.erb
<div class="logmod">
  <div class="logmod__wrapper">
    <span class="logmod__close"><a href="/"></a>Close</span>
    
    <div class="logmod__container">
      <ul class="logmod__tabs">
        <li data-tabtar="lgm-2"><%= link_to volunteer_register_path do %> Sign In <span class="fa fa-sign-in"></span><% end %></li>
        <li data-tabtar="lgm-1"><%= link_to volunteer_register_path do %> Sign Up <span class="fa fa-lock"></span><% end %></li>
      </ul>
    <div class="logmod__tab-wrapper">
      <div class="logmod__tab lgm-2">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">Enter your email and password <strong>to sign in</strong></span>
        </div>
        <div class="logmod__form">
          <%= form_for @contituent, url: {action: "login"} do |f| %>
          <!--%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %-->
            <div class="sminputs">
              <div class="input full">
                  <%= f.label :email, :class => 'string optional' %>
                  <%= f.email_field :email, :id => 'user-email', :class => 'string optional', :placeholder => 'Email', autofocus: true %>
                </div>
            </div>
            <div class="sminputs">
              <div class="input full">
                <%= f.label :password, :class => 'string optional', :for => 'user-pw' %>
                <%= f.password_field :password, :class => 'string optional', :id => 'user-pw', :placeholder => 'Password', autocomplete: "off", :type => 'password' %><span class="hide-password"></span>
              </div>
            </div>
            <div class="simform__actions">
                <%= f.submit "Log in", :class => 'submit', :class => 'btn btn-success btn-lg pull-right', :type => 'submit' %>
                <span class="simform__actions-sidetext"><a class="special" role="link" href="#">Forgot your password?<br>Click here</a></span>
            </div>
            <% end %>
        </div> 
      </div>


      <div class="logmod__tab lgm-1">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">Enter your personal details <strong>to create an acount</strong></span>
        </div>
        <div class="logmod__form">
          <%= form_for @contituent, url: {action: "new"} do |f| %>
            <div class="sminputs">
              <div class="input full">
                <%= f.label :name %>
                <%= f.text_area :name %></br>
              </div>
            </div>

              <div class="sminputs">
              <div class="input full">
                <%= f.label :password, :class => 'string optional', :for => 'user-pw' %>
                <%= f.password_field :password %></br>
              </div>
            </div>
              <div class="sminputs">
              <div class="input full">
                <%= f.label :avaliability_date %>
                <%= f.date_field :avaliability_date %></br>
              </div>
            </div>
            <div class="sminputs">
              <div class="input full">
                <%= check_box_tag(:preference_one) %>
                <%= label_tag(:preference_one, "Traveling") %>
              </div>
            </div>
            <div class="sminputs">
              <div class="input full">
                <%= check_box_tag(:preference_two) %>
                    <%= label_tag(:preference_one, "Reading") %>
              </div>     
              <div class="input full">
                <%= check_box_tag(:preference_one) %>
                    <%= label_tag(:preference_one, "Cooking") %>
              </div>
            </div>
      

             <div class="sminputs">
              <div class="input full">
                <%= f.label :phone %>
                    <%= f.text_area :phone %></br>
              </div>
            </div>
             <div class="sminputs">
              <div class="input full">
                <%= f.label :gender %>
                    <%= f.text_area :gender %></br>
              </div>
            </div>
             <div class="sminputs">
              <div class="input full">
                <%= f.label :referee_name %>
                    <%= f.text_area :referee_name%></br>
              </div>
            </div>
             <div class="sminputs">
              <div class="input full">
               <%= f.label :refree_email %>
                    <%= f.text_area :refree_email%></br>
              </div>
            </div>
             <div class="sminputs">
              <div class="input full">
                <%= f.label :referee_description %>
                    <%= f.text_area :referee_description %></br>
              </div>
            </div>

            <div class="simform__actions">
                <%= f.submit "Submit", :class => 'submit', :class => 'btn btn-success btn-lg pull-right', :type => 'submit' %>
                <span class="simform__actions-sidetext">By creating an account you agree to our <a class="special" href="#" target="_blank" role="link">Terms &amp; Privacy</a></span>
            </div>
            <% end %>       
        </div>
      </div>
      </div>
    </div>
  </div>
</div> 

app/views/contituent/profile.html.erb
<h1>Profile<h1>

app/views/contituent/reviews.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">
<!--<![endif]-->
<head>
</head>
<body>
	<form action="#">

  <header>
    <h2>Let us know</h2>
    <div>Let me know what do you think after the call.</div>
  </header>
      
  <div>
    <fieldset>
    
      <legend id="title5" class="desc">
        Rate your partner today.
      </legend>
 
      <div>
		<ul>
			<input id="radioDefault_5" name="Field5" type="hidden" value="">
			<div>
				<input id="Field5_0" name="Field5" type="radio" value="5" tabindex="5" checked="checked">
				<label class="choice" for="Field5_0">Very happy</label>
			</div>
			<div>
				<input id="Field5_1" name="Field5" type="radio" value="4" tabindex="6">
				<label class="choice" for="Field5_1">happy</label>
			</div>
			<div>
				<input id="Field5_2" name="Field5" type="radio" value="3" tabindex="7">
				<label class="choice" for="Field5_2">So so</label>
			</div>
			<div>
				<input id="Field5_3" name="Field5" type="radio" value="2" tabindex="7">
				<label class="choice" for="Field5_2">Unhappy</label>
			</div>
			<div>
				<input id="Field5_4" name="Field5" type="radio" value="1" tabindex="7">
				<label class="choice" for="Field5_2">Very unhappy</label>
			</div>
		</ul>
      </div>
    </fieldset>
  </div>
    
  <div>
    <label class="desc" id="title4" for="Field4">
      Your comment
    </label>
  
    <div>
      <textarea id="Field4" name="Field4" spellcheck="true" rows="10" cols="50" tabindex="4"></textarea>
    </div>
  </div>

  <div>
		<div>
  		<input id="saveForm" name="saveForm" type="submit" value="Submit">
    </div>
	</div>
  <style>
* {
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}

body {
  padding: 20px 15%;
}
form header {
  margin: 0 0 20px 0; 
}
form header div {
  font-size: 90%;
  color: #999;
}
form header h2 {
  margin: 0 0 5px 0;
}
form > div {
  clear: both;
  overflow: hidden;
  padding: 1px;
  margin: 0 0 10px 0;
}
form > div > fieldset > div > div {
  margin: 0 0 5px 0;
}
form > div > label,
legend {
	width: 25%;
  float: left;
  padding-right: 10px;
}
form > div > div,
form > div > fieldset > div {
  width: 75%;
  float: right;
}
form > div > fieldset label {
	font-size: 90%;
}
fieldset {
	border: 0;
  padding: 0;
}

input[type=text],
input[type=email],
input[type=url],
input[type=password],
textarea {
	width: 100%;
  border-top: 1px solid #ccc;
  border-left: 1px solid #ccc;
  border-right: 1px solid #eee;
  border-bottom: 1px solid #eee;
}
input[type=text],
input[type=email],
input[type=url],
input[type=password] {
  width: 50%;
}
input[type=text]:focus,
input[type=email]:focus,
input[type=url]:focus,
input[type=password]:focus,
textarea:focus {
  outline: 0;
  border-color: #4697e4;
}

@media (max-width: 600px) {
  form > div {
    margin: 0 0 15px 0; 
  }
  form > div > label,
  legend {
	  width: 100%;
    float: none;
    margin: 0 0 5px 0;
  }
  form > div > div,
  form > div > fieldset > div {
    width: 100%;
    float: none;
  }
  input[type=text],
  input[type=email],
  input[type=url],
  input[type=password],
  textarea,
  select {
    width: 100%; 
  }
}
@media (min-width: 1200px) {
  form > div > label,
	legend {
  	text-align: right;
  }
}
</style>
</form>
</body>
</html>

app/views/contituent/settings.html.erb
<h1>Setting<h1>

app/views/contituent/show.html.erb
<h1> Constituent Registration </h1>

app/views/pages/index.html.erb
<!DOCTYPE html>
<html lang="en" class="no-js">
<!--<![endif]-->
<head>
    <meta charset="UTF-8">    
    <%= favicon_link_tag 'logo.png', :rel => 'icon', :type => 'image/png' %>

    <title>YouYom - Simplifying Shopping Experience</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />

    <%= csrf_meta_tags %>

   <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <!--%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

</head>

<body>
    <div class="pre-loader">
        <div class="load-con">
            <%= image_tag 'logo.png', :class => 'animated fadeInDown' %>

            <div class="spinner">
                <div class="bounce1"></div>
            </div>
        </div>
    </div>
    <div class="go-down">
        <a href="#about">
            <i class="fa fa-angle-down fa-3x"></i>
        </a>
    </div>
    <!-- Wrap all page content here -->
    <div id="wrap" class="home">

        <header class="masthead">
            <div class="slider-container" id="slider">
                <div class="tp-banner-container">
                    <div class="tp-banner">
                        <ul>
                            <li data-transition="slotfade-horizontal" data-slotamount="7" data-masterspeed="500">
                                <!-- MAIN IMAGE -->
                                	<%= image_tag 'newImage.png', :alt => 'slidebg1' %>
                             
                            </li>
                        </ul>
                        <div class="tp-bannertimer"></div>
                    </div>
                </div>
            </div>

            <!-- Fixed navbar -->
            <div class="navbar navbar-static-top" id="nav" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                            <span class="sr-only">Toggle navigation</span>
                            <i class="fa fa-align-justify"></i>
                        </button>
                        <a class="navbar-brand" href="#slider">

                        	<%= image_tag 'logo.png', :alt => "" %>
                        </a>
                    </div>

                    <!-- Collect the nav links, forms, and other content for toggling -->
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="active"><a href="#slider">Home</a>
                            </li>
                            <li><a href="#about">about</a>
                            </li>
                            <li><a href="#features">features</a>
                            </li>
                            <!--li><a href="#steps">Steps</a>
                            </li-->
                            <li><a href="#">Register / Sign In </a>
							    <ul>
                                <%= link_to volunteer_register_path do %>
                                    Volunteers <% end %>
                                <%= link_to contituent_register_path do %>
                                    Constituents <% end %>
							    </ul>
							  </li>
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </div>
                <!--/.container -->
            </div>
            <!--/.navbar -->
        </header>
    </div>
    <div class="wrapper">
        <section id="about">
            <div class="container">
                <div class="section-heading scrollpoint sp-effect3">                
                    <h1>About Us</h1>
                    <div class="divider"></div>
                    <p>We help more than 5m people every year to<br> provide support, companionship &amp; advice for older people</p>
                </div>
                <div class="row">
        		<div class="col-md-3 col-sm-3 col-xs-6">
                        <div class="about-item scrollpoint sp-effect2">
                            <i class="fa fa-phone fa-2x"></i><br/>
                            <h3>Call Service</h3>
                            <p>We inspire older people to get active and be healthier, offer a telephone befriending service to tackle loneliness and isolation</p>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-6" >
                        <div class="about-item scrollpoint sp-effect5">
                            <i class="fa fa-mobile fa-2x"></i><br/>
                            <h3>Support</h3>
                            <p>With more than 170 local partners, we can give you the vital services you need locally</p>
                        </div>
                    </div>

       
                    <div class="col-md-3 col-sm-3 col-xs-6" >
                        <div class="about-item scrollpoint sp-effect5">
                            <i class="fa fa-users fa-2x"></i>

                            <h3>Social support</h3>
                            <p>We provide financial and non-financial support to our local and international partners to help them provide more and better services for older people in their local area </p>
                        </div>
                    </div>
                    <div class="col-md-3 col-sm-3 col-xs-6" >
                        <div class="about-item scrollpoint sp-effect1">
                            <i class="fa fa-connectdevelop fa-2x"></i><br/>
                            <h3>Connect</h3>
                            <p>Why not help us to make the most of later life for everyone by becoming part of our organisation</p>
            
                        </div>
                    </div>
                </div>
            </div>
        </section>

        <section id="features">
            <div class="container">
                <div class="section-heading scrollpoint sp-effect3">
                    <h1>Features</h1>
                    <div class="divider"></div>
                    <p>App functionalities </p>
                </div>
                <div class="row">
                    <div class="col-md-4 col-sm-4 scrollpoint sp-effect1">
                        <div class="media text-right feature">
                            <a class="pull-right">
                                <i class="fa fa-home fa-2x"></i>
                            </a>
                            <div class="media-body">
                                <h3 class="media-heading">Home</h3><br/>
                                See your activity records.
                            </div>
                        </div>
                        <div class="media text-right feature">
                            <a class="pull-right">
                                <i class="fa fa-user fa-2x"></i>
                            </a>
                            <div class="media-body">
                                <h3 class="media-heading">Profile</h3><br/>
                                Update your profile.
                            </div>
                        </div>
                        <div class="media text-right feature">
                            <a class="pull-right">
                                <i class="fa fa-cogs fa-2x"></i>
                            </a>
                            <div class="media-body">
                                <h3 class="media-heading">Settings</h3><br/>
                                Adjust your preferences.
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-sm-4" >
                    	<%= image_tag 'android.png', :class => 'img-responsive scrollpoint sp-effect5' %>
                    </div>
                    <div class="col-md-4 col-sm-4 scrollpoint sp-effect2">
                        <div class="media feature">
                            <a class="pull-left">
                                <i class="fa fa-info-circle fa-2x"></i>
                            </a>
                            <div class="media-body">
                                <h3 class="media-heading">Help</h3><br/>
                                Get in touch with local admin.
                            </div>
                        </div>
                        <div class="media feature">
                            <a class="pull-left">
                                <i class="fa fa-calendar-check-o fa-2x"></i>
                            </a>
                            <div class="media-body">
                                <h3 class="media-heading">Schedule™</h3><br/>
                                Update your availability.
                            </div>
                        </div>
                        
                        <div class="media active feature">
                            <a class="pull-left">
                                <i class="fa fa-plus fa-2x"></i>
                            </a>
                            <div class="media-body">
                                <h3 class="media-heading">And much more!</h3><br/>
                                Yes, much more...
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        

        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-md-4">
                        <span class="copyright">Copyright &copy; AgeUK 2015</span>
                    </div>
                    <div class="col-md-4">
                        <ul class="list-inline medias">
                            <li><a href="https://www.facebook.com/ageuk/"><i class="fa fa-facebook fa-1x"></i></a>
                            </li>
                            <li><a href="https://twitter.com/ageuk"><i class="fa fa-twitter fa-1x"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="col-md-4">
                        <ul class="list-inline links">
                            <li><a href="#">Privacy Policy</a>
                            </li>
                            <li><a href="#">Terms of Use</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </footer>
</div>
    <!--/wrap-->

    <script>
    $(document).ready(function() {
        appMaster.preLoader();
        appMaster.smoothScroll();
        appMaster.scrollMenu();
        appMaster.animateScript();
        appMaster.navSpy();
        appMaster.revSlider();
        appMaster.stellar();
        appMaster.maps();
        appMaster.isoTop();
        appMaster.canvasHack();
        appMaster.placeHold();
    });
    </script>
</body>
</html>

app/views/volunteer/new.html.erb
<div class="logmod">
  <div class="logmod__wrapper">
    <span class="logmod__close"><a href="/"></a>Close</span>
    
    <div class="logmod__container">
      <ul class="logmod__tabs">
        <li data-tabtar="lgm-2"><%= link_to volunteer_register_path do %> Sign In <span class="fa fa-sign-in"></span><% end %></li>
        <li data-tabtar="lgm-1"><%= link_to volunteer_register_path do %> Sign Up <span class="fa fa-lock"></span><% end %></li>
      </ul>
    <div class="logmod__tab-wrapper">
      <div class="logmod__tab lgm-2">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">Enter your email and password <strong>to sign in</strong></span>
        </div>
        <div class="logmod__form">
          <%= form_for @volunteer, url: {action: "login"} do |f| %>
          <!--%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %-->
            <div class="sminputs">
              <div class="input full">
                  <%= f.label :email, :class => 'string optional' %>
                  <%= f.email_field :email, :id => 'user-email', :class => 'string optional', :placeholder => 'Email', autofocus: true %>
                </div>
            </div>
            <div class="sminputs">
              <div class="input full">
                <%= f.label :password, :class => 'string optional', :for => 'user-pw' %>
                <%= f.password_field :password, :class => 'string optional', :id => 'user-pw', :placeholder => 'Password', autocomplete: "off", :type => 'password' %><span class="hide-password"></span>
              </div>
            </div>
            <div class="simform__actions">
              
                <%= f.submit "Log in", :class => 'submit', :class => 'btn btn-success btn-lg pull-right', :type => 'submit' %> 

                <span class="simform__actions-sidetext"><a class="special" role="link" href="#">Forgot your password?<br>Click here</a></span>
            </div>
            <% end %>
        </div> 
      </div>


      <div class="logmod__tab lgm-1">
        <div class="logmod__heading">
          <span class="logmod__heading-subtitle">Enter your personal details <strong>to create an acount</strong></span>
        </div>
        <div class="logmod__form">
          <%= form_for @volunteer, url: {action: "new"} do |f| %>
            <div class="sminputs">
              <div class="input full">
                <%= f.label :name %>
                <%= f.text_area :name %></br>
              </div>
            </div>

              <div class="sminputs">
              <div class="input full">
                <%= f.label :password, :class => 'string optional', :for => 'user-pw' %>
                <%= f.password_field :password %></br>
              </div>
            </div>
              <div class="sminputs">
              <div class="input full">
                <%= f.label :avaliability_date %>
                <%= f.date_field :avaliability_date %></br>
              </div>
            </div>
            <div class="sminputs">
              <div class="input full">
                <%= check_box_tag(:preference_one) %>
                <%= label_tag(:preference_one, "Traveling") %>
              </div>
            </div>
            <div class="sminputs">
              <div class="input full">
                <%= check_box_tag(:preference_two) %>
                    <%= label_tag(:preference_one, "Reading") %>
              </div>     
              <div class="input full">
                <%= check_box_tag(:preference_one) %>
                    <%= label_tag(:preference_one, "Cooking") %>
              </div>
            </div>
      

             <div class="sminputs">
              <div class="input full">
                <%= f.label :phone %>
                    <%= f.text_area :phone %></br>
              </div>
            </div>
             <div class="sminputs">
              <div class="input full">
                <%= f.label :gender %>
                    <%= f.text_area :gender %></br>
              </div>
            </div>
             <div class="sminputs">
              <div class="input full">
                <%= f.label :referee_name %>
                    <%= f.text_area :referee_name%></br>
              </div>
            </div>
             <div class="sminputs">
              <div class="input full">
               <%= f.label :refree_email %>
                    <%= f.text_area :refree_email%></br>
              </div>
            </div>
             <div class="sminputs">
              <div class="input full">
                <%= f.label :referee_description %>
                    <%= f.text_area :referee_description %></br>
              </div>
            </div>

            <div class="simform__actions">
                <%= f.submit "Submit", :class => 'submit', :class => 'btn btn-success btn-lg pull-right', :type => 'submit' %>
                <span class="simform__actions-sidetext">By creating an account you agree to our <a class="special" href="#" target="_blank" role="link">Terms &amp; Privacy</a></span>
            </div>
            <% end %>       
        </div>
      </div>
      </div>
    </div>
  </div>
</div> 